### ISSUE TITLE
Unable to compile for UE5.2

### ISSUE THREAD

**Issue by bvaibhav1** [microsoft/MixedRealityToolkit-Unreal#23]
Hello, 

We have been unable to compile hololens on ue5.2. Is it even possible?

Any tips will be helpful.

**Comment by bvaibhav1** [comment]
i updated the string to 5.2 in plugin but getting and error Engine\Plugins\Runtime\OpenXR\Source\OpenXRHMD\Public\OpenXRCore.h(15): error C2065: 'XR_ERROR_SPACE_COMPONENT_NOT_SUPPORTED_FB': undeclared identifie

**Comment by peterclemenko** [comment]
How do you compile it anyway, i'm curious about that because i'm trying to do the same thing, get it working on 5.2

**Comment by bvaibhav1** [comment]
You need to compile using visual studio, by changing target from Win64/ to HL

**Comment by peterclemenko** [comment]
is it still broken, or did you figure out how to compile it?

**Comment by peterclemenko** [comment]
also, does it need a source build of unreal engine?
